package com.example.wifidrop

import java.io.File

enum class ChatChannel(private val titleResource: Int) {
    DIRECT(R.string.pr_chat_direct),
    GLOBAL(R.string.pr_chat_channel);

    val title: String get() = appString(titleResource)
}

data class P2pScreenState(
    val permissionGranted: Boolean,
    val permissionName: String,
    val p2pEnabled: Boolean,
    val lanConnected: Boolean,
    val lanLocalIp: String?,
    val lanScanStatus: String,
    val lanScanning: Boolean,
    val statusMessage: String,
    val quickHint: String,
    val thisDeviceName: String,
    val thisDeviceAddress: String,
    val peers: List<PeerDevice>,
    val connection: ConnectionSnapshot?,
    val directDiscovering: Boolean,
    val directConnecting: Boolean,
    val directCreatingGroup: Boolean,
    val authToken: String,
    val sessionPin: String,
    val sessionExpiresAtMs: Long,
    val nowMs: Long,
    val sessionExpired: Boolean,
    val localDeviceIdShort: String,
    val tokenSyncStatus: String,
    val targetIp: String,
    val suggestedTargetIp: String?,
    val resolvedTargetIp: String?,
    val resolvedTargetLabel: String?,
    val resolvedTargetMode: ConnectionMode?,
    val directTargetIp: String?,
    val directTargetLabel: String?,
    val chatDirectTargetIp: String?,
    val chatDirectTargetIps: List<String>,
    val chatDirectTargetLabel: String?,
    val chatDirectTargetMode: ConnectionMode?,
    val chatDirectAvailablePeers: List<KnownPeerSnapshot>,
    val lastPeerLabel: String?,
    val knownServicePeers: List<KnownPeerSnapshot>,
    val pendingTrust: PendingTrustRequest?,
    val pendingCredentialShare: PendingCredentialShareRequest?,
    val trustedPeers: List<TrustedPeer>,
    val favoritePeers: List<TrustedPeer>,
    val favoriteSuggestionPeerId: String?,
    val favoriteSuggestionLabel: String?,
    val lastSendTargetIp: String?,
    val lastSendTargetLabel: String?,
    val receiving: Boolean,
    val receiverStatus: String,
    val receiverProgress: Float?,
    val receiverFileName: String?,
    val receiverInstantBps: Long,
    val receiverAverageBps: Long,
    val receiverEtaSeconds: Long?,
    val receiverFailureCause: String?,
    val receivedFiles: List<File>,
    val selectedFileNames: List<String>,
    val selectedFilesCount: Int,
    val sending: Boolean,
    val sendActiveCount: Int,
    val sendBatchTotal: Int,
    val sendBatchCompleted: Int,
    val sendBatchFailed: Int,
    val sendBatchCanceled: Int,
    val sendQueue: List<SendQueueItemSnapshot>,
    val sendProgress: Float,
    val sendStatus: String,
    val sendInstantBps: Long,
    val sendAverageBps: Long,
    val sendEtaSeconds: Long?,
    val sendFailureCause: String?,
    val shareImportStatus: String,
    val paused: Boolean,
    val history: List<TransferHistoryEntry>,
    val chatChannel: ChatChannel,
    val globalLanJoined: Boolean,
    val globalChatPeerCount: Int,
    val directChannelPeerCount: Int,
    val chatDraft: String,
    val chatMessages: List<ChatMessageEntry>,
    val messageStatus: String,
    val activeConnectionMode: ConnectionMode,
    val connectionViewMode: ConnectionViewMode,
    val wifiDirectModeEnabled: Boolean,
    val lanModeEnabled: Boolean,
    val fontScale: Float,
    val compactMode: Boolean,
    val vibrateOnConnect: Boolean,
    val vibrateOnError: Boolean,
    val silentSuccessFeedback: Boolean,
    val autoDownloadChannelFiles: Boolean,
    val attachmentContext: com.example.wifidrop.presentation.P2pAttachmentContext = com.example.wifidrop.presentation.P2pAttachmentContext.FILES,
    val incomingShareEventId: Long? = null,
    val sessionReady: Boolean = false,
    val chatSessionReady: Boolean = false,
    val sessionEnabled: Boolean = true,
    val sessionSyncing: Boolean = false
)
