package com.example.wifidrop

import com.example.wifidrop.presentation.localizeKnownStatus
import java.util.Locale

/** Display-only translations. Keep the original exception and persisted/wire codes unchanged. */
internal fun runtimeFailureText(raw: String?): String {
    val value = raw?.trim().orEmpty()
    if (value.isEmpty()) return appString(R.string.rt_error_unknown)
    runtimeErrorResources[value.lowercase(Locale.ROOT)]?.let { return appString(it) }
    val prefixErrors = listOf(
        "Receptor rechazo archivo: " to R.string.rt_error_file_rejected,
        "Receptor rechazo mensaje: " to R.string.rt_error_message_rejected,
        "HELLO rechazado: " to R.string.rt_error_hello_rejected,
        "emparejamiento_manual_requerido: " to R.string.rt_error_manual_pairing
    )
    prefixErrors.firstOrNull { value.startsWith(it.first, ignoreCase = true) }?.let { (prefix, resource) ->
        return appString(resource, runtimeFailureText(value.substring(prefix.length)))
    }
    when {
        value.startsWith("transferencia incompleta para ") -> {
            val detail = value.removePrefix("transferencia incompleta para ")
            return appString(R.string.rt_error_incomplete_transfer, detail.substringBeforeLast(": "), detail.substringAfterLast(": "))
        }
        value.startsWith("integridad SHA-256 invalida para ") ->
            return appString(R.string.rt_error_invalid_integrity, value.removePrefix("integridad SHA-256 invalida para "))
        value.startsWith("respuesta invalida (packet=") ->
            return appString(R.string.rt_error_invalid_packet, value.removePrefix("respuesta invalida (packet=").removeSuffix(")"))
        value.startsWith("estado Noise invalido: ") ->
            return appString(R.string.rt_error_invalid_noise_state, value.removePrefix("estado Noise invalido: "))
        value.startsWith("frame seguro invalido: ") ->
            return appString(R.string.rt_error_invalid_secure_frame, value.removePrefix("frame seguro invalido: "))
    }
    // A history entry or retained state may already have display copy in the previous locale.
    return localizeKnownStatus(value, runtimeErrorStringResources, intArrayOf()) { resource, index, argument ->
        if (index == 0 && resource in runtimeNestedErrorResources) runtimeFailureText(argument) else argument
    }
}

private val runtimeNestedErrorResources = setOf(
    R.string.rt_error_file_rejected, R.string.rt_error_message_rejected,
    R.string.rt_error_hello_rejected, R.string.rt_error_manual_pairing
)

private val runtimeErrorResources = mapOf(
    "error_desconocido" to R.string.rt_error_unknown,
    "fallo de red desconocido" to R.string.rt_error_unknown,
    "error" to R.string.rt_error_unknown,
    "cancelado por usuario" to R.string.rt_error_canceled,
    "cancelado" to R.string.rt_error_canceled,
    "mensaje eliminado" to R.string.rt_error_message_deleted,
    "chat limpiado por usuario" to R.string.rt_error_chat_cleared,
    "equipo olvidado" to R.string.rt_error_device_forgotten,
    "sesion detenida" to R.string.rt_error_session_stopped,
    "exportacion cancelada; archivo original conservado" to R.string.rt_error_export_canceled,
    "vencido: mas de 24h en cola" to R.string.rt_error_queue_expired,
    "agotado: maximo 4 reintentos" to R.string.rt_error_retries_exhausted,
    "grupo_direct_no_acreditado" to R.string.rt_error_direct_group_unverified,
    "grupo_direct_renovado" to R.string.rt_error_direct_group_changed,
    "destino_fuera_grupo_direct" to R.string.rt_error_outside_direct_group,
    "canal_no_unido" to R.string.rt_error_channel_not_joined,
    "identidad de remitente invalida" to R.string.rt_error_sender_identity,
    "identidad de oferta invalida" to R.string.rt_error_offer_identity,
    "identidad de solicitud invalida" to R.string.rt_error_request_identity,
    "id de transferencia invalido" to R.string.rt_error_transfer_id,
    "id de mensaje invalido" to R.string.rt_error_message_id,
    "el archivo cambio durante el envio. vuelve a seleccionarlo." to R.string.rt_error_file_changed,
    "no se pudo abrir inputstream del archivo" to R.string.rt_error_open_file,
    "version de qetara incompatible. introduce token y pin manualmente." to R.string.rt_error_incompatible_manual,
    "respuesta de emparejamiento invalida" to R.string.rt_error_pairing_response,
    "identidad noise ausente" to R.string.rt_error_noise_identity_missing,
    "noise_key_mismatch" to R.string.rt_error_noise_key_changed,
    "clave noise no coincide para peer confiado" to R.string.rt_error_noise_key_changed,
    "sesion_expirada" to R.string.rt_error_session_expired,
    "sesion expirada" to R.string.rt_error_session_expired,
    "sesion expirada en host" to R.string.rt_error_session_expired,
    "respuesta de credenciales invalida" to R.string.rt_error_credentials_response,
    "respuesta de credenciales cifradas invalida" to R.string.rt_error_credentials_response,
    "no se pudo crear la carpeta de recepcion" to R.string.rt_error_receive_folder,
    "carpeta de recepcion no disponible" to R.string.rt_error_receive_folder,
    "no autorizada" to R.string.rt_error_unauthorized,
    "protocolo no valido" to R.string.rt_error_invalid_protocol,
    "version de protocolo no compatible" to R.string.rt_error_incompatible_protocol,
    "secure_credentials_required" to R.string.rt_error_secure_credentials_required,
    "confirmacion_host_requerida" to R.string.rt_error_host_confirmation,
    "dispositivo_no_confiable" to R.string.rt_error_untrusted_device,
    "tipo de paquete no soportado" to R.string.rt_error_unsupported_packet,
    "auth_invalida" to R.string.rt_error_invalid_authentication,
    "autenticacion invalida" to R.string.rt_error_invalid_authentication,
    "frame hello invalido" to R.string.rt_error_invalid_hello,
    "frame message invalido" to R.string.rt_error_invalid_message_frame,
    "file_error" to R.string.rt_error_file_error,
    "message_error" to R.string.rt_error_message_error,
    "frame file_meta invalido" to R.string.rt_error_invalid_file_metadata_frame,
    "tamano invalido para archivo" to R.string.rt_error_invalid_file_size,
    "tamano de archivo invalido" to R.string.rt_error_invalid_file_size,
    "metadatos de archivo invalidos" to R.string.rt_error_invalid_file_metadata,
    "se esperaba confirmacion de archivo completado" to R.string.rt_error_missing_file_confirmation,
    "carpeta temporal no disponible" to R.string.rt_error_temporary_folder,
    "ruta temporal no permitida" to R.string.rt_error_temporary_path,
    "no se pudo restablecer el archivo parcial" to R.string.rt_error_reset_partial,
    "longitud de chunk invalida" to R.string.rt_error_invalid_chunk,
    "chunk de archivo invalido" to R.string.rt_error_invalid_chunk,
    "transferencia excede tamano esperado" to R.string.rt_error_excess_file_size,
    "frame inesperado durante archivo" to R.string.rt_error_unexpected_file_frame,
    "posicion de reanudacion invalida" to R.string.rt_error_invalid_resume,
    "frame file_resume invalido" to R.string.rt_error_invalid_resume,
    "no se pudo reanudar: faltan bytes por saltar" to R.string.rt_error_resume_missing_bytes,
    "respuesta invalida (magic)" to R.string.rt_error_invalid_response_magic,
    "respuesta invalida (version)" to R.string.rt_error_invalid_response_version,
    "respuesta inesperada" to R.string.rt_error_unexpected_response,
    "frame result invalido" to R.string.rt_error_invalid_result_frame,
    "frame de handshake invalido" to R.string.rt_error_invalid_handshake,
    "frame seguro demasiado grande" to R.string.rt_error_secure_frame_large,
    "mac noise invalida" to R.string.rt_error_invalid_noise_mac,
    "frame noise invalido" to R.string.rt_error_invalid_noise_frame,
    "archivo verificado incompleto" to R.string.rt_error_verified_file_incomplete,
    "destino de recibo invalido" to R.string.rt_error_receipt_destination,
    "carpeta de recibos no disponible" to R.string.rt_error_receipt_folder,
    "archivo temporal inexistente" to R.string.rt_error_temporary_file_missing,
    "ruta de archivo no permitida" to R.string.rt_error_file_path_not_allowed,
    "demasiados archivos con el mismo nombre" to R.string.rt_error_file_name_collisions,
    "no se pudo publicar el archivo verificado" to R.string.rt_error_publish_verified_file,
    "espacio insuficiente para recibir el archivo" to R.string.rt_error_insufficient_space,
    "archivo origen no disponible" to R.string.rt_error_source_file_unavailable,
    "carpeta de exportacion no disponible" to R.string.rt_error_export_folder,
    "copia local incompleta" to R.string.rt_error_incomplete_copy,
    "hash de archivo invalido" to R.string.rt_error_invalid_file_hash,
    "token invalido. usa 4-32 caracteres a-z y 0-9." to R.string.rt_error_invalid_token,
    "pin invalido. usa 6 digitos." to R.string.rt_error_invalid_pin,
    "clientid vacio" to R.string.rt_error_empty_client_id,
    "mensaje vacio" to R.string.rt_error_empty_message,
    "mensaje demasiado largo" to R.string.rt_error_message_too_long,
    "socket closed" to R.string.rt_error_socket_closed,
    "socket is closed" to R.string.rt_error_socket_closed,
    "connection reset" to R.string.rt_error_connection_reset,
    "connection reset by peer" to R.string.rt_error_connection_reset,
    "sockettimeoutexception" to R.string.rt_error_timeout,
    "read timed out" to R.string.rt_error_timeout,
    "connect timed out" to R.string.rt_error_timeout,
    "timeout" to R.string.rt_error_timeout,
    "connection refused" to R.string.rt_error_connection_refused,
    "connectexception" to R.string.rt_error_connection_refused,
    "network is unreachable" to R.string.rt_error_network_unreachable,
    "no route to host" to R.string.rt_error_network_unreachable,
    "noroutetohostexception" to R.string.rt_error_network_unreachable,
    "eofexception" to R.string.rt_error_unexpected_end
)

private val runtimeErrorStringResources = intArrayOf(
    R.string.rt_invalid_source_file,
    R.string.rt_create_download_failed,
    R.string.rt_open_download_failed,
    R.string.rt_publish_download_failed,
    R.string.rt_error_unknown,
    R.string.rt_error_canceled,
    R.string.rt_error_message_deleted,
    R.string.rt_error_chat_cleared,
    R.string.rt_error_device_forgotten,
    R.string.rt_error_session_stopped,
    R.string.rt_error_export_canceled,
    R.string.rt_error_queue_expired,
    R.string.rt_error_retries_exhausted,
    R.string.rt_error_direct_group_unverified,
    R.string.rt_error_direct_group_changed,
    R.string.rt_error_outside_direct_group,
    R.string.rt_error_channel_not_joined,
    R.string.rt_error_sender_identity,
    R.string.rt_error_offer_identity,
    R.string.rt_error_request_identity,
    R.string.rt_error_transfer_id,
    R.string.rt_error_message_id,
    R.string.rt_error_file_changed,
    R.string.rt_error_open_file,
    R.string.rt_error_incompatible_manual,
    R.string.rt_error_pairing_response,
    R.string.rt_error_noise_identity_missing,
    R.string.rt_error_noise_key_changed,
    R.string.rt_error_session_expired,
    R.string.rt_error_credentials_response,
    R.string.rt_error_receive_folder,
    R.string.rt_error_unauthorized,
    R.string.rt_error_invalid_protocol,
    R.string.rt_error_incompatible_protocol,
    R.string.rt_error_secure_credentials_required,
    R.string.rt_error_host_confirmation,
    R.string.rt_error_untrusted_device,
    R.string.rt_error_unsupported_packet,
    R.string.rt_error_invalid_authentication,
    R.string.rt_error_invalid_hello,
    R.string.rt_error_invalid_message_frame,
    R.string.rt_error_file_error,
    R.string.rt_error_message_error,
    R.string.rt_error_invalid_file_metadata_frame,
    R.string.rt_error_invalid_file_size,
    R.string.rt_error_invalid_file_metadata,
    R.string.rt_error_missing_file_confirmation,
    R.string.rt_error_temporary_folder,
    R.string.rt_error_temporary_path,
    R.string.rt_error_reset_partial,
    R.string.rt_error_invalid_chunk,
    R.string.rt_error_excess_file_size,
    R.string.rt_error_unexpected_file_frame,
    R.string.rt_error_invalid_resume,
    R.string.rt_error_resume_missing_bytes,
    R.string.rt_error_invalid_response_magic,
    R.string.rt_error_invalid_response_version,
    R.string.rt_error_unexpected_response,
    R.string.rt_error_invalid_result_frame,
    R.string.rt_error_invalid_handshake,
    R.string.rt_error_secure_frame_large,
    R.string.rt_error_invalid_noise_mac,
    R.string.rt_error_invalid_noise_frame,
    R.string.rt_error_verified_file_incomplete,
    R.string.rt_error_receipt_destination,
    R.string.rt_error_receipt_folder,
    R.string.rt_error_temporary_file_missing,
    R.string.rt_error_file_path_not_allowed,
    R.string.rt_error_file_name_collisions,
    R.string.rt_error_publish_verified_file,
    R.string.rt_error_insufficient_space,
    R.string.rt_error_source_file_unavailable,
    R.string.rt_error_export_folder,
    R.string.rt_error_incomplete_copy,
    R.string.rt_error_invalid_file_hash,
    R.string.rt_error_invalid_token,
    R.string.rt_error_invalid_pin,
    R.string.rt_error_empty_client_id,
    R.string.rt_error_empty_message,
    R.string.rt_error_message_too_long,
    R.string.rt_error_socket_closed,
    R.string.rt_error_connection_reset,
    R.string.rt_error_timeout,
    R.string.rt_error_connection_refused,
    R.string.rt_error_network_unreachable,
    R.string.rt_error_unexpected_end,
    R.string.rt_error_file_rejected,
    R.string.rt_error_message_rejected,
    R.string.rt_error_hello_rejected,
    R.string.rt_error_manual_pairing,
    R.string.rt_error_incomplete_transfer,
    R.string.rt_error_invalid_integrity,
    R.string.rt_error_invalid_packet,
    R.string.rt_error_invalid_noise_state,
    R.string.rt_error_invalid_secure_frame
)
